#!/bin/bash
#PBS -N deepcon
#PBS -l nodes=1:ppn=32
#PBS -l walltime=240:00:00
#PBS -W x=GRES:gpu@1
#PBS -q gpu-2-1
#PBS -V
#PBS -S /bin/bash

cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee /tmp/nodes.$$ | wc -l`
cat "$PBS_NODEFILE" |uniq  > /tmp/nodefile.$$

module load tensorflow/tensorflow-gpu-2.0.0-py36

python runDEEPCON.py  > deepcon.log

rm -rf /tmp/nodefile.$$
echo "Your job is done."
exit 0