#!/bin/bash
#PBS -N hmm_ccmpred
#PBS -l nodes=1:ppn=32
#PBS -l walltime=240:00:00  
#PBS -q cu-1
#PBS -V
#PBS -S /bin/bash
cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee /tmp/nodes.$$ | wc -l`
cat "$PBS_NODEFILE" |uniq  > /tmp/nodefile.$$

module load pytorch/pytorch-gpu-1.10.0-py37 
module load python/3.6.10
python  hmm_ccmpred_train.py >hmm_ccmpred.log
